name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install utilities
        run: sudo apt-get update && sudo apt-get install -y wget unzip zip

      - name: Install Android SDK command line tools & platforms
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmd.zip
          unzip -q cmd.zip
          mv cmdline-tools latest || true
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Add local.properties pointing to SDK
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Download Gradle 8.2.1 and add to PATH
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.2.1-bin.zip -O gradle.zip
          unzip -q gradle.zip -d gradle-dist
          echo "GRADLE_HOME=${{ github.workspace }}/gradle-dist/gradle-8.2.1" >> $GITHUB_ENV
          echo "${{ github.workspace }}/gradle-dist/gradle-8.2.1/bin" >> $GITHUB_PATH

      - name: Ensure gradlew executable (if present)
        run: chmod +x ./gradlew || true

      - name: Build debug APK
        run: gradle assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: sakura-apk
          path: app/build/outputs/apk/debug/app-debug.apk
